### PR TITLE
Avoid a NULL pointer deref when reading os-release

### PR DESCRIPTION
**Pull request by ngie-eign**

### CODE REVIEW

**Comment by vincentbernat** [comment]
Ack for the code change, but for `.gitignore`, you can avoid that by using an out-of-build tree:

**Comment by ngie-eign** [comment]
> Ack for the code change, but for `.gitignore`, you can avoid that by using an out-of-build tree:
> 
> ```
> mkdir build
> cd build
> ../configure ...
> ```
> 
> This reduces the maintenance burden on `.gitignore`.

I suppose so. I've gotten used to projects not fully supporting that out of the box.

**Comment by vincentbernat** [comment]
Thanks!

**Comment by ngie-eign** [comment]
Ughhh.. I probably should have added a NULL check for the next strtok call 🤦. I’ll submit a patch for that too.

**Pull request merged**
