### PR TITLE
lldpd:Device hangs after running LLDP suite in Defensics fuzz tool

### PR DESCRIPTION
**Pull request by sudhanshukumar22**
Running Defensics LLDP suite often hangs the device and only way to retrieve it back is by power cycling the device.

As the device hangs and there is no access to Console/Mgmt Sessions, not able to take tech-support output in problem state.

Attaching the pcap files of LLDP packets from Defensics server, as the  report doesn't contain any failures.

Also attaching the syslog output before/at the time hitting problem state.

Additionally, I checked if there are any sporadic CPU/Memory hike while running and did not notice any.

Only once seen lldp crash and attaching the same as well.
Fix: added a validation check in MED processing in lldp_decode().
Signed-off-by: sudhanshukumar22 <sudhanshu.kumar@broadcom.com>

### CODE REVIEW

**Comment by vincentbernat** [comment]
Thanks for your patch. However, it only works when the location is a civic address. The two other possibilities (coordinate and ELIN) does use the first byte as a length. In `lldp.c`, no decoding is done, so an incorrect value shouldn't matter. Also, looking in `atom/med.c`, I see the length is just ignored (we rely on the len of the TLV, which is not totally correct). Do you have a PCAP showing a packet exhibiting a problem?

**Comment by sudhanshukumar22** [comment]
> Thanks for your patch. However, it only works when the location is a civic address. The two other possibilities (coordinate and ELIN) does use the first byte as a length. In `lldp.c`, no decoding is done, so an incorrect value shouldn't matter. Also, looking in `atom/med.c`, I see the length is just ignored (we rely on the len of the TLV, which is not totally correct). Do you have a PCAP showing a packet exhibiting a problem?

I am attaching the lldp packet capture:
[mgmt ip change issue.zip](https://github.com/lldpd/lldpd/files/5636441/mgmt.ip.change.issue.zip)

**Comment by vincentbernat** [comment]
Thanks, I am running into a bit of trouble to run some tests. Hopefully, this will be solved next week.

**Comment by vincentbernat** [comment]
If you can run again the test suite, it will be helpful to catch remaining bugs!

**Comment by sudhanshukumar22** [comment]
@vincentbernat : Does your pull request 422 fix this issue ?

**Comment by vincentbernat** [comment]
Yes, it should. I was able to reproduce your issue.

**Pull request closed without merging**
