### PR TITLE
lldpd: mgmt-ip info showing invalid ip in lldp neighbors output

### PR DESCRIPTION
**Pull request by sudhanshukumar22**
Problem Description/Summary :
--------------------------------------------
mgmt-ip info showing invalid ip in lldp neighborship output.

Expected Behavior :
------------------------
mgmt-ip should be same in both show lldp neighbors and ifconfig eth0

Topology :
------------
2DUT

Fix: Update the management ip.
Verified LLDP neighbor information has the mgmt interface IP only, verified reboot and docker restart cases as well.
Signed-off-by: sudhanshukumar22 <sudhanshu.kumar@broadcom.com>

### CODE REVIEW

**Comment by vincentbernat** [comment]
You can configure the management IP using `configure system ip management pattern`. Depending on the system, this could be the one on `eth0` or not. Hard-coding `eth0` is not possible.

**Comment by vincentbernat** [comment]
lldpd runs on any Linux/BSD. One some of them, the management interface will be on `vlan100`, on others `em0`, on others `eno3`. There is no universal rule.

I understand the management pattern is not enough in your case. I can introduce a way to specify an interface name instead of an IP address. In this case, you can ship lldpd with the option set to `eth0`. Would this matches your use case?

**Comment by sudhanshukumar22** [comment]
> lldpd runs on any Linux/BSD. One some of them, the management interface will be on `vlan100`, on others `em0`, on others `eno3`. There is no universal rule.
> 
> I understand the management pattern is not enough in your case. I can introduce a way to specify an interface name instead of an IP address. In this case, you can ship lldpd with the option set to `eth0`. Would this matches your use case?

Do you want to introduce another CLI  to specify the interface name for management interface ? I think that should help, but problem is user may not enter that CLI. In that case, we have to take the ip address from some fixed interface (like eth0).

**Comment by vincentbernat** [comment]
❦  3 décembre 2020 05:44 -08, sudhanshukumar22:

>> I understand the management pattern is not enough in your case. I
>> can introduce a way to specify an interface name instead of an IP
>> address. In this case, you can ship lldpd with the option set to
>> `eth0`. Would this matches your use case?
>
> Do you want to introduce another CLI to specify the interface name for
> management interface ?

Yes.

> I think that should help, but problem is user may not enter that CLI.

If you distribute lldpd as part of your platform, you can ship a
/etc/lldpd.d/lldpd.conf with the command preinstalled. The user can
override it if they want.

> In that case, we have to take the ip address from some fixed interface
> (like eth0).

There are so many systems without an eth0 interface that it does not
seem the right heuristic. The current heuristic is to use the first IP
address. This heuristic is more than 10 years old.

I think it should work in your case too if eth0 is the first interface
on your system. However, if you use DHCP for eth0 and have static IP,
lldpd will not change back to the IP on eth0 once it gets a management
interface. A work-around would be to restart lldpd on DHCP leases.

**Comment by sudhanshukumar22** [comment]
@vincentbernat : "However, if you use DHCP for eth0 and have static IP,
lldpd will not change back to the IP on eth0 once it gets a management
interface. A work-around would be to restart lldpd on DHCP leases."

By static IP, do you mean that user has configured ip address in LLDP using "configure system ip management pattern" ? Also, I don't understand "lldpd will not change back to the IP". is it because of CLI configuration in LLDP ?

**Comment by vincentbernat** [comment]
❦  3 décembre 2020 06:11 -08, sudhanshukumar22:

> @vincentbernat : "However, if you use DHCP for eth0 and have static IP,
> lldpd will not change back to the IP on eth0 once it gets a management
> interface. A work-around would be to restart lldpd on DHCP leases."
>
> By static IP, do you mean that user has configured ip address in LLDP
> using "configure system ip management pattern" ? Also, I don't
> understand "lldpd will not change back to the IP". is it because of
> CLI configuration in LLDP ?

For example, if eth0 is using DHCP, but you have swp1 with a static IP
address (set outside lldpd), lldpd will select swp1 IP address as the
management IP address as this is the first one. When eth0 gets its DHCP
address, lldpd will not switch back to the IP address of eth0 because it
won't change the management IP address once it has one. However, once
eth0 has its IP address, if you restart lldpd, it will likely use the
one from eth0 (it really depends if it's the first in the output of "ip
a s").

**Comment by sudhanshukumar22** [comment]
@vincentbernat : I assume that you want this fix to be reworked as follows:
1. Introduce a lldp cli to set the management interface, where we configure the ip address. 
2. add a line in /etc/lldpd.d/lldpd.conf

**Comment by vincentbernat** [comment]
For 1, the CLI would be to specify the interface to use to take the management address. There is already a CLI to force the IP address. I can do that if you are not in a hurry.

**Comment by sudhanshukumar22** [comment]
My point was this PR has to be discarded. Is that correct ?

**Comment by vincentbernat** [comment]
We can keep it like an issue until we fix it. But, yes, the code part of this PR can be discarded.

**Comment by vincentbernat** [comment]
Tell me if you plan to implement it, so that both of us don't work on it at the same time.

Thanks.

**Comment by sudhanshukumar22** [comment]
Hi, We will take it up.

**Comment by sudhanshukumar22** [comment]
> Tell me if you plan to implement it, so that both of us don't work on it at the same time.
> 
> Thanks.



> Tell me if you plan to implement it, so that both of us don't work on it at the same time.
> 
> Thanks.

@vincentbernat : Hi Vincent, after having a discussion in the team and considering other priorities, can you please take up this issue ?

**Comment by vincentbernat** [comment]
❦ 22 décembre 2020 05:42 -08, sudhanshukumar22:

>> Tell me if you plan to implement it, so that both of us don't work on it at the same time.
>> 
>> Thanks.
>
> @vincentbernat : Hi Vincent, after having a discussion in the team and
> considering other priorities, can you please take up this issue ?

Yes, I can, allow me a couple of weeks.

**Comment by vincentbernat** [comment]
So, while trying to implement it, I have discovered this is already supported. You can either run `lldpd` with `-m eth0` or you can use `configure system ip management pattern eth0`.

**Comment by sudhanshukumar22** [comment]
@vincentbernat : I hope the work for this is more than implementing the CLI. The work may involve changing the lldpd.conf file to configure the default interface as eth0 (we can use the same CLI mentioned in your comments).

**Comment by vincentbernat** [comment]
As said previously, I won't change the default to `eth0` as it would break existing setups and many devices don't use `eth0`, including Linux devices.

**Pull request closed without merging**
