### PR TITLE
feat: Add lldpctl C++ wrapper

### PR DESCRIPTION
**Pull request by rbu9fe**
In case you're interested here is a C++ wrapper that supports automatic lifetime management of the underlying resources. For C++ projects that greatly simplifies resource management.

Some features are not yet available, I just wanted to get early feedback whether you're interested in integrating that wrapper.

### CODE REVIEW

**Comment by vincentbernat** [comment]
Yes, I can take it.

**Comment by rbu9fe** [comment]
How can a `lldpctl_change_callback2` callback be unregistered again? By closing the underlying connection? Is that even allowed (since the doc says not to use that connection for anything else besides receiving notifications)?

**Comment by vincentbernat** [comment]
You can unregister by passing NULL, but it won't remove the state allowing to use the connection for anything else. Maybe this could be reusable, but I think there may be a race condition if a notification is ongoing. Better close the connection.

**Comment by rbu9fe** [comment]
The C++ wrapper is now ready. It comes with some convenience features like managing the lifetime of an atom's underlying connection or of its parent atom (if available).

An atom's value can be retrieved as a `std::string`, `std::string_view`, `int` or as a `std::span<std::byte>`. Atom lists can be get as `std::vector`.

Note: Stopping the watcher thread doesn't work yet as the underlying `lldpctl_watch` doesn't unblock, therefore, that must be fixed in the C library.

**Comment by rbu9fe** [comment]
Solved stopping the watcher thread by using `lldpctl_watch_sync_unblock` from [this PR](https://github.com/lldpd/lldpd/pull/696). Therefore, that PR must be merged before this C++ wrapper.

**Comment by vincentbernat** [comment]
Could you rebase your PR? Thanks.

**Comment by rbu9fe** [comment]
Done.

**Comment by vincentbernat** [comment]
Thanks. I'll see if I am able to keep it up-to-date.

**Pull request merged**
